kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.pv.name }}
  labels:
    type: {{ .Values.pv.labelType }}
spec:
  storageClassName: {{ .Values.pv.storageClassName}}
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - {{ .Values.pv.accessMode }}
  hostPath:
    path: {{ .Values.pv.hostPath }}