apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.appName}}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appName}}
        tier: backend
    spec:
      containers:
        - name: {{ .Values.deployment.appName}}
          image: "{{ .Values.deployment.imageName }}:{{ .Values.deployment.imageTag }}"
          imagePullPolicy: {{ .Values.deployment.pullPolicy }}
          env:
            - name: MONGO_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: MONGO_DB_HOST
            - name: MONGO_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: MONGO_DB_PORT
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: MONGO_DB_NAME
            - name: MONGO_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: MONGO_DB_USERNAME
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: MONGODB_URI
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: MONGO_DB_PASSWORD
          ports:
            - containerPort: {{ .Values.deployment.container.containerPort }}
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}