# Generated by Django 4.2.2 on 2023-06-29 04:19

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2023)),
                ("month", models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_plan",
                    models.CharField(
                        choices=[
                            ("Debt Payments", "Debt Payments"),
                            ("Investing", "Investing"),
                            ("Saving", "Saving"),
                            ("Housing", "Housing"),
                            ("Food", "Food"),
                            ("Utilities", "Utilities"),
                            ("Medical & Healthcare", "Medical & Healthcare"),
                            ("Personal Spending", "Personal Spending"),
                            (
                                "Recreation & Entertainment",
                                "Recreation & Entertainment",
                            ),
                            ("Miscellaneous", "Miscellaneous"),
                        ]
                    ),
                ),
                (
                    "amount_plan",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(1000000.0),
                        ]
                    ),
                ),
                (
                    "date_plan",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 6, 29, 4, 19, 0, 838494, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "date_period",
                    models.ForeignKey(
                        default=datetime.datetime(
                            2023, 6, 29, 4, 19, 0, 838494, tzinfo=datetime.timezone.utc
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.periodtime",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_income", models.CharField(max_length=30)),
                (
                    "amount_income",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(1000000.0),
                        ]
                    ),
                ),
                (
                    "date_income",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 6, 29, 4, 19, 0, 837497, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "date_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.periodtime",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_plan",
                    models.CharField(
                        choices=[
                            ("Debt Payments", "Debt Payments"),
                            ("Investing", "Investing"),
                            ("Saving", "Saving"),
                            ("Housing", "Housing"),
                            ("Food", "Food"),
                            ("Utilities", "Utilities"),
                            ("Medical & Healthcare", "Medical & Healthcare"),
                            ("Personal Spending", "Personal Spending"),
                            (
                                "Recreation & Entertainment",
                                "Recreation & Entertainment",
                            ),
                            ("Miscellaneous", "Miscellaneous"),
                        ]
                    ),
                ),
                (
                    "amount_expense",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(1000000.0),
                        ]
                    ),
                ),
                (
                    "date_expense",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 6, 29, 4, 19, 0, 838494, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "date_period",
                    models.ForeignKey(
                        default=datetime.datetime(
                            2023, 6, 29, 4, 19, 0, 838494, tzinfo=datetime.timezone.utc
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.periodtime",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
