# Generated by Django 3.2 on 2024-02-24 17:14

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024)),
                ('month', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_plan', models.CharField(choices=[('Debt Payments', 'Debt Payments'), ('Investing', 'Investing'), ('Saving', 'Saving'), ('Housing', 'Housing'), ('Food', 'Food'), ('Utilities', 'Utilities'), ('Medical & Healthcare', 'Medical & Healthcare'), ('Personal Spending', 'Personal Spending'), ('Recreation & Entertainment', 'Recreation & Entertainment'), ('Miscellaneous', 'Miscellaneous')], max_length=100)),
                ('amount_plan', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1000000.0)])),
                ('date_plan', models.DateField(default=datetime.datetime(2024, 2, 24, 17, 14, 15, 381567, tzinfo=utc))),
                ('date_period', models.ForeignKey(default=datetime.datetime(2024, 2, 24, 17, 14, 15, 381467, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='finance.periodtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_income', models.CharField(max_length=30)),
                ('amount_income', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1000000.0)])),
                ('date_income', models.DateField(default=datetime.datetime(2024, 2, 24, 17, 14, 15, 380868, tzinfo=utc))),
                ('date_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.periodtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_plan', models.CharField(choices=[('Debt Payments', 'Debt Payments'), ('Investing', 'Investing'), ('Saving', 'Saving'), ('Housing', 'Housing'), ('Food', 'Food'), ('Utilities', 'Utilities'), ('Medical & Healthcare', 'Medical & Healthcare'), ('Personal Spending', 'Personal Spending'), ('Recreation & Entertainment', 'Recreation & Entertainment'), ('Miscellaneous', 'Miscellaneous')], max_length=100)),
                ('amount_expense', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1000000.0)])),
                ('date_expense', models.DateField(default=datetime.datetime(2024, 2, 24, 17, 14, 15, 382427, tzinfo=utc))),
                ('date_period', models.ForeignKey(default=datetime.datetime(2024, 2, 24, 17, 14, 15, 382339, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='finance.periodtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
