# Generated by Django 4.2.2 on 2023-06-26 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date_expense",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 26, 17, 22, 34, 533324, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date_period",
            field=models.ForeignKey(
                default=datetime.datetime(
                    2023, 6, 26, 17, 22, 34, 533324, tzinfo=datetime.timezone.utc
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.periodtime",
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="date_income",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 26, 17, 22, 34, 532327, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="date_period",
            field=models.ForeignKey(
                default=datetime.datetime(
                    2023, 6, 26, 17, 22, 34, 532327, tzinfo=datetime.timezone.utc
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.periodtime",
            ),
        ),
        migrations.AlterField(
            model_name="periodtime",
            name="month",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 26, 17, 22, 34, 532327, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="periodtime",
            name="year",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 26, 17, 22, 34, 532327, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="date_period",
            field=models.ForeignKey(
                default=datetime.datetime(
                    2023, 6, 26, 17, 22, 34, 532327, tzinfo=datetime.timezone.utc
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="finance.periodtime",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="date_plan",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 26, 17, 22, 34, 532327, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
