# Generated by Django 3.2 on 2024-02-25 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_expense',
            field=models.DateField(default=datetime.datetime(2024, 2, 25, 13, 13, 35, 102860, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_period',
            field=models.ForeignKey(default=datetime.datetime(2024, 2, 25, 13, 13, 35, 102817, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='finance.periodtime'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_income',
            field=models.DateField(default=datetime.datetime(2024, 2, 25, 13, 13, 35, 102068, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date_period',
            field=models.ForeignKey(default=datetime.datetime(2024, 2, 25, 13, 13, 35, 102376, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='finance.periodtime'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date_plan',
            field=models.DateField(default=datetime.datetime(2024, 2, 25, 13, 13, 35, 102430, tzinfo=utc)),
        ),
    ]
