# Generated by Django 3.2 on 2024-02-25 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20240225_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_expense',
            field=models.DateField(default=datetime.datetime(2024, 2, 25, 13, 23, 39, 569411, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_period',
            field=models.ForeignKey(default=datetime.datetime(2024, 2, 25, 13, 23, 39, 569372, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='finance.periodtime'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_income',
            field=models.DateField(default=datetime.datetime(2024, 2, 25, 13, 23, 39, 568685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date_period',
            field=models.ForeignKey(default=datetime.datetime(2024, 2, 25, 13, 23, 39, 568972, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='finance.periodtime'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date_plan',
            field=models.DateField(default=datetime.datetime(2024, 2, 25, 13, 23, 39, 569018, tzinfo=utc)),
        ),
    ]
