# Generated by Django 3.2 on 2024-02-25 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20240225_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_expense',
            field=models.DateField(default=datetime.datetime(2024, 2, 25, 13, 27, 9, 169052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_period',
            field=models.ForeignKey(default=datetime.datetime(2024, 2, 25, 13, 27, 9, 169009, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='finance.periodtime'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_income',
            field=models.DateField(default=datetime.datetime(2024, 2, 25, 13, 27, 9, 168302, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date_period',
            field=models.ForeignKey(default=datetime.datetime(2024, 2, 25, 13, 27, 9, 168594, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='finance.periodtime'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date_plan',
            field=models.DateField(default=datetime.datetime(2024, 2, 25, 13, 27, 9, 168643, tzinfo=utc)),
        ),
    ]
