version: "3.9"

services:


  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db


  my-postgres:
    image: postgres:latest
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ods:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "fin_cander_db", "-U", "postgres"]
      interval: 20s
      retries: 3
      start_period: 15s
      timeout: 5s

  django-app:
    build:
      context: .
    container_name: my-django-app
    ports:
      - "8000:8000"
    depends_on:
      - my-postgres
      - mongo
    volumes:
      - .:/app
    healthcheck:
      test: curl --fail http://localhost:8000/home/ || exit 1
      interval: 20s
      retries: 3
      start_period: 20s
      timeout: 5s

volumes:
  ods:
  mongodata: