apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-cander-kub
  labels:
    app: fin-cander-kub
    group: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fin-cander-kub
  template:
    metadata:
      labels:
        app: fin-cander-kub
        group: db
    spec:
      containers:
        - name: fin-cander-kub
          image: docker.io/library/fin-1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fin-cander-secrets
                  key: SECRET_KEY
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fin-cander-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: fin-cander-config
                  key: POSTGRES_USER
            - name: POSTGRES_NAME
              valueFrom:
                configMapKeyRef:
                  name: fin-cander-config
                  key: POSTGRES_NAME
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: fin-cander-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: fin-cander-config
                  key: POSTGRES_PORT
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"