apiVersion: v1
kind: Service
metadata:
  name: fin-cander-kub
  labels:
    group: db
spec:
  type: ClusterIP
  selector:             # indicates into which pods ClusterIP provides access
    app: fin-cander-kub
  ports:
    - port: 8000          # port exposed outside ClusterIP
      targetPort: 8000    # port exposed by Pod