kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-v2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/some-space/postgres-pv"