kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-newclaim-v2
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: postgres-pv-volume-v2