kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-v2  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/some-space/postgres-pv"